#!/usr/bin/env python3
"""Train a Qwen/Gemma-compatible LoRA adapter for TorontoView council agents.

Run this on the DGX only. The default dataset is generated by:
  npm run prepare:agent-council-lora

The script intentionally trains behavior and response format, not memorized
Toronto facts. Official factual grounding remains in the RAG corpus.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset", default="data/agent-council/lora/all.jsonl")
    parser.add_argument("--output-dir", default="models/agent-council-lora")
    parser.add_argument("--base-model", default=os.environ.get("LORA_BASE_MODEL", "Qwen/Qwen2.5-7B-Instruct"))
    parser.add_argument("--max-seq-length", type=int, default=int(os.environ.get("LORA_MAX_SEQ_LENGTH", "4096")))
    parser.add_argument("--epochs", type=float, default=float(os.environ.get("LORA_EPOCHS", "1")))
    parser.add_argument("--batch-size", type=int, default=int(os.environ.get("LORA_BATCH_SIZE", "2")))
    parser.add_argument("--grad-accum", type=int, default=int(os.environ.get("LORA_GRAD_ACCUM", "8")))
    parser.add_argument("--learning-rate", type=float, default=float(os.environ.get("LORA_LEARNING_RATE", "2e-4")))
    parser.add_argument("--max-steps", type=int, default=int(os.environ.get("LORA_MAX_STEPS", "0")))
    return parser.parse_args()


def load_rows(path: Path) -> list[dict]:
    rows: list[dict] = []
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            if line.strip():
                rows.append(json.loads(line))
    return rows


def messages_to_text(tokenizer, messages: list[dict]) -> str:
    if hasattr(tokenizer, "apply_chat_template"):
        return tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=False)
    parts = []
    for message in messages:
        parts.append(f"<|{message['role']}|>\n{message['content']}")
    return "\n".join(parts)


def main() -> None:
    args = parse_args()
    dataset_path = Path(args.dataset)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    try:
        from datasets import Dataset
        from trl import SFTTrainer, SFTConfig
        from unsloth import FastLanguageModel
    except ImportError as error:
        raise SystemExit(
            "Missing training dependencies. On the DGX, install/activate an environment with "
            "unsloth, trl, transformers, accelerate, peft, and datasets."
        ) from error

    rows = load_rows(dataset_path)
    if not rows:
        raise SystemExit(f"No rows found in {dataset_path}")

    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=args.base_model,
        max_seq_length=args.max_seq_length,
        dtype=None,
        load_in_4bit=True,
    )
    model = FastLanguageModel.get_peft_model(
        model,
        r=16,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
        lora_alpha=16,
        lora_dropout=0,
        bias="none",
        use_gradient_checkpointing="unsloth",
        random_state=3407,
    )

    dataset = Dataset.from_list([
        {"text": messages_to_text(tokenizer, row["messages"]), "agent": row.get("agent", "unknown")}
        for row in rows
    ])

    config = SFTConfig(
        output_dir=str(output_dir),
        dataset_text_field="text",
        max_seq_length=args.max_seq_length,
        per_device_train_batch_size=args.batch_size,
        gradient_accumulation_steps=args.grad_accum,
        num_train_epochs=args.epochs,
        learning_rate=args.learning_rate,
        max_steps=args.max_steps if args.max_steps > 0 else -1,
        logging_steps=10,
        save_strategy="epoch",
        optim="adamw_8bit",
        seed=3407,
        report_to=[],
    )
    trainer = SFTTrainer(model=model, tokenizer=tokenizer, train_dataset=dataset, args=config)
    trainer.train()
    trainer.save_model(str(output_dir))
    tokenizer.save_pretrained(str(output_dir))

    manifest = {
        "baseModel": args.base_model,
        "dataset": str(dataset_path),
        "rows": len(rows),
        "outputDir": str(output_dir),
        "purpose": "TorontoView council behavior LoRA; factual grounding remains RAG.",
    }
    (output_dir / "torontoview-lora-manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(json.dumps(manifest, indent=2))


if __name__ == "__main__":
    main()
